/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResenasRouteImport } from './routes/resenas'
import { Route as IndexRouteImport } from './routes/index'

const ResenasRoute = ResenasRouteImport.update({
  id: '/resenas',
  path: '/resenas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resenas': typeof ResenasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resenas': typeof ResenasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resenas': typeof ResenasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resenas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resenas'
  id: '__root__' | '/' | '/resenas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResenasRoute: typeof ResenasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resenas': {
      id: '/resenas'
      path: '/resenas'
      fullPath: '/resenas'
      preLoaderRoute: typeof ResenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResenasRoute: ResenasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
